"""Generate lean_export/Jc.lean — a self-contained Lean 4 certificate.

Run with: uv run python -m jc.lean_export

The generated file needs no imports (no Std, no Mathlib) and no axioms.
It defines a computable sparse polynomial algebra over Int, states the
counterexample map F as literal monomial data (extracted here from sympy,
but re-verified inside Lean), and kernel-checks:

  1. det J(F) = -2 as a normal-form equality of formal polynomials,
     with the Jacobian entries produced by an in-file formal derivative;
  2. F(0,0,1) = F(i/2, 3i, -26) evaluated in Gaussian rationals;
  3. the two witness points differ — hence F is not injective.

Only the ~100 lines of Lean definitions need auditing; everything else
is decided by the kernel. sympy is untrusted here: if the extracted
monomial data were wrong, theorem 1 would simply fail to check.
"""

from pathlib import Path

import sympy as sp

from jc.map import F, x, y, z

CORPUS_PATH = Path(__file__).resolve().parents[2] / "lean_export" / "Jc.lean"

_HEADER = """\
/-
  Generated by `uv run python -m jc.lean_export` -- do not edit by hand.

  A machine-checked certificate for the Alpöge–Fable counterexample to
  the Jacobian conjecture (2026): a polynomial map F : C^3 -> C^3 with
  constant Jacobian determinant -2 that is not injective.

  Lean core only: this file needs no `import`, no Std and no Mathlib.
  No `axiom`, no `sorry`. All arithmetic is decided by the kernel.
-/

set_option maxRecDepth 100000
"""

_MACHINERY = """
/-! ### Sparse trivariate polynomials over Int

A polynomial is a list of monomials `((i, j, k), c)` meaning `c·x^i·y^j·z^k`.
`norm` sorts monomials into strictly increasing lex order on exponents,
combining duplicates and dropping zero coefficients, so normal forms are
canonical and polynomial equality is literal list equality. -/

abbrev Exp := Nat × Nat × Nat
abbrev Mono := Exp × Int
abbrev Poly := List Mono

def expLt : Exp → Exp → Bool
  | (a1, a2, a3), (b1, b2, b3) =>
    Nat.blt a1 b1 || (a1 == b1 && (Nat.blt a2 b2 || (a2 == b2 && Nat.blt a3 b3)))

def insertMono (m : Mono) : Poly → Poly
  | [] => if m.2 == 0 then [] else [m]
  | n :: rest =>
    if m.1 == n.1 then
      let c := m.2 + n.2
      if c == 0 then rest else (m.1, c) :: rest
    else if expLt m.1 n.1 then
      if m.2 == 0 then n :: rest else m :: n :: rest
    else
      n :: insertMono m rest

def norm (p : Poly) : Poly := p.foldr insertMono []

def padd (p q : Poly) : Poly := norm (p ++ q)

def pneg (p : Poly) : Poly := p.map (fun m => (m.1, -m.2))

def psub (p q : Poly) : Poly := padd p (pneg q)

def mmul : Mono → Mono → Mono
  | ((i1, j1, k1), c1), ((i2, j2, k2), c2) => ((i1 + i2, j1 + j2, k1 + k2), c1 * c2)

def pmul (p q : Poly) : Poly :=
  norm (p.foldr (fun m acc => q.map (mmul m) ++ acc) [])

/-! ### Formal partial derivatives -/

def pderivX : Poly → Poly
  | [] => []
  | ((0, _, _), _) :: rest => pderivX rest
  | ((Nat.succ i, j, k), c) :: rest => ((i, j, k), c * Int.ofNat (i + 1)) :: pderivX rest

def pderivY : Poly → Poly
  | [] => []
  | ((_, 0, _), _) :: rest => pderivY rest
  | ((i, Nat.succ j, k), c) :: rest => ((i, j, k), c * Int.ofNat (j + 1)) :: pderivY rest

def pderivZ : Poly → Poly
  | [] => []
  | ((_, _, 0), _) :: rest => pderivZ rest
  | ((i, j, Nat.succ k), c) :: rest => ((i, j, k), c * Int.ofNat (k + 1)) :: pderivZ rest

def det3 (a b c d e f g h i : Poly) : Poly :=
  psub
    (padd (pmul a (psub (pmul e i) (pmul f h)))
          (pmul c (psub (pmul d h) (pmul e g))))
    (pmul b (psub (pmul d i) (pmul f g)))

/-! ### Dyadic Gaussian rationals, for evaluating F at the witness points

`⟨a, b, k⟩` denotes (a + b·i) / 2^k. Core `Rat` is avoided because its
gcd-based normalization does not reduce well in the kernel; here `reduce`
strips factors of 2 by parity alone, so every operation kernel-computes
and canonical forms make structural equality coincide with value equality
(k = 0, or a and b not both even). -/

structure GRat where
  a : Int
  b : Int
  k : Nat
deriving DecidableEq, Repr

def reduce : Int → Int → Nat → GRat
  | a, b, 0 => ⟨a, b, 0⟩
  | a, b, Nat.succ k =>
    if a % 2 == 0 && b % 2 == 0 then reduce (a / 2) (b / 2) k else ⟨a, b, Nat.succ k⟩

def pow2 : Nat → Int
  | 0 => 1
  | Nat.succ n => 2 * pow2 n

def gadd (x y : GRat) : GRat :=
  reduce (x.a * pow2 y.k + y.a * pow2 x.k) (x.b * pow2 y.k + y.b * pow2 x.k) (x.k + y.k)

def gmul (x y : GRat) : GRat :=
  reduce (x.a * y.a - x.b * y.b) (x.a * y.b + x.b * y.a) (x.k + y.k)

def gofInt (c : Int) : GRat := ⟨c, 0, 0⟩

def gpow (g : GRat) : Nat → GRat
  | 0 => ⟨1, 0, 0⟩
  | Nat.succ n => gmul g (gpow g n)

abbrev G3 := GRat × GRat × GRat

def evalPoly (p : Poly) (v : G3) : GRat :=
  p.foldr
    (fun m acc =>
      gadd (gmul (gofInt m.2)
        (gmul (gpow v.1 m.1.1) (gmul (gpow v.2.1 m.1.2.1) (gpow v.2.2 m.1.2.2))))
        acc)
    ⟨0, 0, 0⟩

def Injective (f : α → β) : Prop := ∀ ⦃a b⦄, f a = f b → a = b
"""

_THEOREMS = """
/-! ### The certificate -/

def jacDet : Poly :=
  det3 (pderivX FA) (pderivY FA) (pderivZ FA)
       (pderivX FB) (pderivY FB) (pderivZ FB)
       (pderivX FC) (pderivY FC) (pderivZ FC)

/-- The Jacobian determinant of F is the constant -2. -/
theorem jacobian_det_eq_neg_two : jacDet = [((0, 0, 0), -2)] := by decide

def Fmap (v : G3) : G3 := (evalPoly FA v, evalPoly FB v, evalPoly FC v)

/-- First witness point: (0, 0, 1). -/
def P1 : G3 := (⟨0, 0, 0⟩, ⟨0, 0, 0⟩, ⟨1, 0, 0⟩)

/-- Second witness point: (i/2, 3i, -26). -/
def P2 : G3 := (⟨0, 1, 1⟩, ⟨0, 3, 0⟩, ⟨-26, 0, 0⟩)

/-- The two witness points collide: F(P1) = F(P2) = (1, 0, 0). -/
theorem collision : Fmap P1 = Fmap P2 := by decide

theorem P1_ne_P2 : P1 ≠ P2 := by decide

/-- The Jacobian conjecture is false: F has constant Jacobian
    determinant -2 yet is not injective. -/
theorem F_not_injective : ¬ Injective Fmap :=
  fun h => absurd (h collision) P1_ne_P2
"""


def _poly_literal(expr):
    """Render a sympy polynomial in x, y, z as a Lean `Poly` literal."""
    poly = sp.Poly(sp.expand(expr), x, y, z)
    terms = []
    for (i, j, k), coeff in sorted(poly.terms()):
        if coeff != sp.Integer(int(coeff)):
            raise ValueError(f"non-integer coefficient {coeff} in {expr}")
        terms.append(f"(({i}, {j}, {k}), {int(coeff)})")
    return "[" + ", ".join(terms) + "]"


def export_corpus():
    a, b, c = F
    data = (
        "\n/-! ### The counterexample map, as monomial data\n\n"
        "  a = (1+xy)³z + y²(1+xy)(4+3xy)\n"
        "  b = y + 3x(1+xy)²z + 3xy²(4+3xy)\n"
        "  c = 2x − 3x²y − x³z -/\n\n"
        f"def FA : Poly := norm {_poly_literal(a)}\n\n"
        f"def FB : Poly := norm {_poly_literal(b)}\n\n"
        f"def FC : Poly := norm {_poly_literal(c)}\n"
    )
    return _HEADER + _MACHINERY + data + _THEOREMS


def write_corpus():
    CORPUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CORPUS_PATH.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(export_corpus())
    return CORPUS_PATH


if __name__ == "__main__":
    print(f"wrote {write_corpus()}")
