"""Generate lean_export/JcChar2.lean — Lean 4 certificate for the unicorn.

Run with: uv run python -m jc.lean_export2

Lean core only, no axioms, no sorry. The kernel decides:
  1. det J(F) = 1 as a formal polynomial identity over F_2 — polynomials
     are XOR-canonical sorted monomial lists, the derivative and 3x3
     determinant are defined in-file;
  2. F(0,0,1) = F(1,0,1) = F(1,1,1) = (1,0,0) on F_2-points (Bool
     arithmetic), with the three points pairwise distinct — and a
     collision of F_2-points is a collision over every extension field,
     so non-injectivity over the algebraic closure follows.

Not formalized here (documented, machine-checked in Python instead): the
generic degree 3 / tameness computation.
"""

from pathlib import Path

from jc.unicorn import UNICORN

CORPUS_PATH = Path(__file__).resolve().parents[2] / "lean_export" / "JcChar2.lean"

_HEADER = """\
/-
  Generated by `uv run python -m jc.lean_export2` -- do not edit by hand.

  Machine-checked certificate for the tame characteristic-2
  counterexample to Adjamagbo's separable Jacobian conjecture:
  an F_2-polynomial self-map of A^3 with Jacobian determinant
  identically 1 whose induced map is not injective — three rational
  points share one image, a collision that persists over every
  extension of F_2. (The generic degree 3 — oddness, hence tameness —
  is certified computationally outside Lean.)

  Lean core only: no `import`, no Std, no Mathlib, no `axiom`,
  no `sorry`. All arithmetic is decided by the kernel.
-/

set_option maxRecDepth 100000
"""

_MACHINERY = """
/-! ### Polynomials over F_2 as XOR-canonical sorted monomial lists -/

abbrev Exp := Nat × Nat × Nat
abbrev Poly := List Exp

def expLt : Exp → Exp → Bool
  | (a1, a2, a3), (b1, b2, b3) =>
    Nat.blt a1 b1 || (a1 == b1 && (Nat.blt a2 b2 || (a2 == b2 && Nat.blt a3 b3)))

def xorInsert (e : Exp) : Poly → Poly
  | [] => [e]
  | f :: rest =>
    if e == f then rest
    else if expLt e f then e :: f :: rest
    else f :: xorInsert e rest

def norm (p : Poly) : Poly := p.foldr xorInsert []

def padd (p q : Poly) : Poly := norm (p ++ q)

def mmul : Exp → Exp → Exp
  | (i1, j1, k1), (i2, j2, k2) => (i1 + i2, j1 + j2, k1 + k2)

def pmul (p q : Poly) : Poly :=
  norm (p.foldr (fun e acc => q.map (mmul e) ++ acc) [])

def pderivX : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if i % 2 == 1 then (i - 1, j, k) :: pderivX rest else pderivX rest

def pderivY : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if j % 2 == 1 then (i, j - 1, k) :: pderivY rest else pderivY rest

def pderivZ : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if k % 2 == 1 then (i, j, k - 1) :: pderivZ rest else pderivZ rest

def det3 (a b c d e f g h i : Poly) : Poly :=
  padd (padd (pmul a (padd (pmul e i) (pmul f h)))
             (pmul b (padd (pmul d i) (pmul f g))))
       (pmul c (padd (pmul d h) (pmul e g)))

/-! ### Evaluation on F_2-points (Bool arithmetic) -/

def bpow (b : Bool) : Nat → Bool
  | 0 => true
  | Nat.succ _ => b

abbrev Pt := Bool × Bool × Bool

def evalPoly (p : Poly) (v : Pt) : Bool :=
  p.foldr
    (fun e acc => xor (bpow v.1 e.1 && bpow v.2.1 e.2.1 && bpow v.2.2 e.2.2) acc)
    false

def Injective (f : α → β) : Prop := ∀ ⦃a b⦄, f a = f b → a = b
"""

_THEOREMS = """
def jacDet : Poly :=
  det3 (pderivX FA) (pderivY FA) (pderivZ FA)
       (pderivX FB) (pderivY FB) (pderivZ FB)
       (pderivX FC) (pderivY FC) (pderivZ FC)

/-- The Jacobian determinant of F is identically 1 over F_2. -/
theorem jacobian_det_eq_one : jacDet = [(0, 0, 0)] := by decide

def Fmap (v : Pt) : Pt := (evalPoly FA v, evalPoly FB v, evalPoly FC v)

def P1 : Pt := (false, false, true)
def P2 : Pt := (true, false, true)
def P3 : Pt := (true, true, true)

/-- Three distinct rational points share the image (1, 0, 0). -/
theorem collision :
    Fmap P1 = (true, false, false) ∧
    Fmap P2 = (true, false, false) ∧
    Fmap P3 = (true, false, false) := by decide

theorem points_distinct : P1 ≠ P2 ∧ P1 ≠ P3 ∧ P2 ≠ P3 := by decide

/-- The induced map on F_2-points is not injective; since the collision
    is between rational points, the polynomial map is non-injective over
    every extension of F_2. -/
theorem F_not_injective : ¬ Injective Fmap :=
  fun h => absurd (h (collision.1.trans collision.2.1.symm)) points_distinct.1
"""


def _poly_literal(comp):
    terms = ", ".join(f"({i}, {j}, {k})" for i, j, k in sorted(comp))
    return f"[{terms}]"


def export_corpus():
    a, b, c = UNICORN
    data = (
        "\n/-! ### The counterexample map, as monomial data over F_2\n\n"
        "  F1 = z + xy + xy² + x²y² + x²yz + x²y²z + x³y²z\n"
        "  F2 = y + xy²\n"
        "  F3 = x + y + xy² + x²z -/\n\n"
        f"def FA : Poly := norm {_poly_literal(a)}\n\n"
        f"def FB : Poly := norm {_poly_literal(b)}\n\n"
        f"def FC : Poly := norm {_poly_literal(c)}\n"
    )
    return _HEADER + _MACHINERY + data + _THEOREMS


def write_corpus():
    CORPUS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with CORPUS_PATH.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(export_corpus())
    return CORPUS_PATH


if __name__ == "__main__":
    print(f"wrote {write_corpus()}")
