/-
  Generated by `uv run python -m jc.lean_export2` -- do not edit by hand.

  Machine-checked certificate for the tame characteristic-2
  counterexample to Adjamagbo's separable Jacobian conjecture:
  an F_2-polynomial self-map of A^3 with Jacobian determinant
  identically 1 whose induced map is not injective — three rational
  points share one image, a collision that persists over every
  extension of F_2. (The generic degree 3 — oddness, hence tameness —
  is certified computationally outside Lean.)

  Lean core only: no `import`, no Std, no Mathlib, no `axiom`,
  no `sorry`. All arithmetic is decided by the kernel.
-/

set_option maxRecDepth 100000

/-! ### Polynomials over F_2 as XOR-canonical sorted monomial lists -/

abbrev Exp := Nat × Nat × Nat
abbrev Poly := List Exp

def expLt : Exp → Exp → Bool
  | (a1, a2, a3), (b1, b2, b3) =>
    Nat.blt a1 b1 || (a1 == b1 && (Nat.blt a2 b2 || (a2 == b2 && Nat.blt a3 b3)))

def xorInsert (e : Exp) : Poly → Poly
  | [] => [e]
  | f :: rest =>
    if e == f then rest
    else if expLt e f then e :: f :: rest
    else f :: xorInsert e rest

def norm (p : Poly) : Poly := p.foldr xorInsert []

def padd (p q : Poly) : Poly := norm (p ++ q)

def mmul : Exp → Exp → Exp
  | (i1, j1, k1), (i2, j2, k2) => (i1 + i2, j1 + j2, k1 + k2)

def pmul (p q : Poly) : Poly :=
  norm (p.foldr (fun e acc => q.map (mmul e) ++ acc) [])

def pderivX : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if i % 2 == 1 then (i - 1, j, k) :: pderivX rest else pderivX rest

def pderivY : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if j % 2 == 1 then (i, j - 1, k) :: pderivY rest else pderivY rest

def pderivZ : Poly → Poly
  | [] => []
  | (i, j, k) :: rest =>
    if k % 2 == 1 then (i, j, k - 1) :: pderivZ rest else pderivZ rest

def det3 (a b c d e f g h i : Poly) : Poly :=
  padd (padd (pmul a (padd (pmul e i) (pmul f h)))
             (pmul b (padd (pmul d i) (pmul f g))))
       (pmul c (padd (pmul d h) (pmul e g)))

/-! ### Evaluation on F_2-points (Bool arithmetic) -/

def bpow (b : Bool) : Nat → Bool
  | 0 => true
  | Nat.succ _ => b

abbrev Pt := Bool × Bool × Bool

def evalPoly (p : Poly) (v : Pt) : Bool :=
  p.foldr
    (fun e acc => xor (bpow v.1 e.1 && bpow v.2.1 e.2.1 && bpow v.2.2 e.2.2) acc)
    false

def Injective (f : α → β) : Prop := ∀ ⦃a b⦄, f a = f b → a = b

/-! ### The counterexample map, as monomial data over F_2

  F1 = z + xy + xy² + x²y² + x²yz + x²y²z + x³y²z
  F2 = y + xy²
  F3 = x + y + xy² + x²z -/

def FA : Poly := norm [(0, 0, 1), (1, 1, 0), (1, 2, 0), (2, 1, 1), (2, 2, 0), (2, 2, 1), (3, 2, 1)]

def FB : Poly := norm [(0, 1, 0), (1, 2, 0)]

def FC : Poly := norm [(0, 1, 0), (1, 0, 0), (1, 2, 0), (2, 0, 1)]

def jacDet : Poly :=
  det3 (pderivX FA) (pderivY FA) (pderivZ FA)
       (pderivX FB) (pderivY FB) (pderivZ FB)
       (pderivX FC) (pderivY FC) (pderivZ FC)

/-- The Jacobian determinant of F is identically 1 over F_2. -/
theorem jacobian_det_eq_one : jacDet = [(0, 0, 0)] := by decide

def Fmap (v : Pt) : Pt := (evalPoly FA v, evalPoly FB v, evalPoly FC v)

def P1 : Pt := (false, false, true)
def P2 : Pt := (true, false, true)
def P3 : Pt := (true, true, true)

/-- Three distinct rational points share the image (1, 0, 0). -/
theorem collision :
    Fmap P1 = (true, false, false) ∧
    Fmap P2 = (true, false, false) ∧
    Fmap P3 = (true, false, false) := by decide

theorem points_distinct : P1 ≠ P2 ∧ P1 ≠ P3 ∧ P2 ≠ P3 := by decide

/-- The induced map on F_2-points is not injective; since the collision
    is between rational points, the polynomial map is non-injective over
    every extension of F_2. -/
theorem F_not_injective : ¬ Injective Fmap :=
  fun h => absurd (h (collision.1.trans collision.2.1.symm)) points_distinct.1
